name = "shaad3d"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Do not commit secrets to this file!
# Use wrangler secret put <NAME> or set them in the Cloudflare dashboard.
# 
# Required secrets for your project:
# SUPABASE_SERVICE_ROLE_KEY
# CLOUDINARY_API_KEY
# CLOUDINARY_API_SECRET

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://bmtqeiwqokpieehdcycb.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtdHFlaXdxb2twaWVlaGRjeWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5NTc4NTEsImV4cCI6MjA5NzUzMzg1MX0.nkSFqbtAzf6CHfrCf_8ddxMHOHi52pD2nI5jJAH8Ik0"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_57ylQlrIkhQ7bVDKpoLvAA_eLQQ0rYB"
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "dqscxwnkb"
